[package]
name = "craft-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "craft_cli"
crate-type = ["cdylib"]

[dependencies]
jiff = "0.2.8"
pyo3 = "0.24.0"
