class Mode:
    BRIEF: ...
    VERBOSE: ...

class MessageType:
    PROG_PERSISTENT: ...
    PROG_EPHEMERAL: ...
    WARNING: ...
    ERROR: ...
    DEBUG: ...
    TRACE: ...
    INFO: ...

class Message:
    message: str
    model: MessageType

    def __init__(self, msg: str, model: MessageType):
        ...

class Printer:
    def __init__(self):
        ...

    def start(self, mode: Mode) -> None:
        ...

    def stop(self) -> None:
        ...

    def send(self, msg: Message) -> None:
        ...
