class Mode:
    Brief: ...
    Verbose: ...

class MessageType:
    ProgPersistent: ...
    ProgEphemeral: ...
    Warning: ...
    Error: ...
    Debug: ...
    Trace: ...
    Info: ...

class Message:
    message: str
    model: MessageType

    def __init__(self, msg: str, model: MessageType) -> None:
        ...

class Printer:
    def __init__(self) -> None:
        ...

    def start(self, mode: Mode) -> None:
        ...

    def stop(self) -> None:
        ...

    def send(self, msg: Message) -> None:
        ...
